#!/usr/bin/env bash
# Hermes E-Ink Dashboard — one-liner installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/NicoMancinelli/hermes-eink-dashboard/main/install.sh | bash
#   curl -fsSL ... | bash -s -- --bind 192.168.1.42 --port 9120
#
# What it does:
#   1. Installs the package into ~/.local/share/hermes-eink-dashboard/venv
#   2. Generates a bearer token at ~/.config/hermes-eink-dashboard/token
#   3. Installs a systemd --user service named hermes-eink-dashboard
#   4. Starts the service on the requested bind/port
#
# Override defaults via flags or env vars (HERMES_EINK_BIND, HERMES_EINK_PORT,
# HERMES_EINK_REFRESH, HERMES_EINK_WIDTH, HERMES_EINK_HEIGHT, HERMES_EINK_CONTEXT_LIMIT,
# HERMES_EINK_HERMES_HOME).
set -euo pipefail

REPO="${HERMES_EINK_REPO:-NicoMancinelli/hermes-eink-dashboard}"
REF="${HERMES_EINK_REF:-main}"

BIND_HOST="${HERMES_EINK_BIND:-127.0.0.1}"
PORT="${HERMES_EINK_PORT:-9120}"
WIDTH="${HERMES_EINK_WIDTH:-1072}"
HEIGHT="${HERMES_EINK_HEIGHT:-1448}"
CONTEXT_LIMIT="${HERMES_EINK_CONTEXT_LIMIT:-262144}"
REFRESH_SECONDS="${HERMES_EINK_REFRESH:-15}"
HERMES_HOME="${HERMES_EINK_HERMES_HOME:-$HOME/.hermes}"
INSTALL_SERVICE="${HERMES_EINK_NO_SERVICE:-1}"

usage() {
  cat <<'EOF'
Options:
  --bind ADDRESS         Bind address (default: 127.0.0.1)
  --port PORT            HTTP port (default: 9120)
  --width PIXELS         Render width (default: 1072)
  --height PIXELS        Render height (default: 1448)
  --context-limit N      Model context window (default: 262144)
  --refresh-seconds N    Hermes refresh interval (default: 15)
  --hermes-home PATH     Hermes home directory (default: ~/.hermes)
  --no-service           Install the package but do not enable systemd service
  -h, --help             Show this help
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bind) BIND_HOST="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --width) WIDTH="$2"; shift 2 ;;
    --height) HEIGHT="$2"; shift 2 ;;
    --context-limit) CONTEXT_LIMIT="$2"; shift 2 ;;
    --refresh-seconds) REFRESH_SECONDS="$2"; shift 2 ;;
    --hermes-home) HERMES_HOME="$2"; shift 2 ;;
    --no-service) INSTALL_SERVICE="0"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

case "$BIND_HOST" in ""|*[!A-Za-z0-9._:-]*)
  echo "bind address contains invalid characters" >&2; exit 2 ;;
esac
case "$PORT" in ""|*[!0-9]*)
  echo "port must be numeric" >&2; exit 2 ;;
esac
case "$PORT" in 0|*) [ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || { echo "port out of range" >&2; exit 2; } ;; esac

for cmd in python3 curl systemctl; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "required command not found: $cmd" >&2
    exit 1
  fi
done

if ! command -v python3 -m venv >/dev/null 2>&1; then
  echo "python3-venv is required (apt install python3-venv)" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required: https://cli.github.com/" >&2
  exit 1
fi

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hermes-eink-dashboard"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/hermes-eink-dashboard"
SERVICE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
TOKEN_FILE="$CONFIG_DIR/token"
ENV_FILE="$CONFIG_DIR/host.env"
VENV="$DATA_DIR/venv"
TMPDIR="$(mktemp -d)" && trap 'rm -rf "$TMPDIR"' EXIT

mkdir -p "$CONFIG_DIR" "$DATA_DIR" "$SERVICE_DIR"

if [ ! -f "$TOKEN_FILE" ]; then
  python3 -c "import secrets; print(secrets.token_urlsafe(32))" > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
fi

if [ ! -d "$VENV" ]; then
  python3 -m venv "$VENV"
fi

# Pull source tarball (no git clone needed).
TARBALL="$TMPDIR/repo.tar.gz"
curl -fsSL "https://codeload.github.com/$REPO/tar.gz/$REF" -o "$TARBALL"
tar -xzf "$TARBALL" -C "$TMPDIR"
SRC_DIR="$(find "$TMPDIR" -maxdepth 1 -type d -name "${REPO##*/}-*" | head -n1)"

# Install package in editable mode from the tarball source.
"$VENV/bin/pip" install --quiet --upgrade "$SRC_DIR"

if [ "$INSTALL_SERVICE" != "1" ]; then
  cat <<EOF
Installed package, but skipped systemd service (--no-service).

To start manually:
  $VENV/bin/hermes-kindle-dashboard \\
    --bind $BIND_HOST --port $PORT --width $WIDTH --height $HEIGHT \\
    --context-limit $CONTEXT_LIMIT --refresh-seconds $REFRESH_SECONDS \\
    --hermes-home "$HERMES_HOME"

Token: $TOKEN_FILE
EOF
  exit 0
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh — do not edit by hand unless you know what you're doing.
HERMES_DASHBOARD_HOST=$BIND_HOST
HERMES_DASHBOARD_PORT=$PORT
HERMES_DASHBOARD_WIDTH=$WIDTH
HERMES_DASHBOARD_HEIGHT=$HEIGHT
HERMES_DASHBOARD_CONTEXT_LIMIT=$CONTEXT_LIMIT
HERMES_DASHBOARD_REFRESH_SECONDS=$REFRESH_SECONDS
HERMES_DASHBOARD_HERMES_HOME=$HERMES_HOME
EOF
chmod 600 "$ENV_FILE"

cat > "$SERVICE_DIR/hermes-eink-dashboard.service" <<EOF
[Unit]
Description=Hermes E-Ink Dashboard
After=network-online.target

[Service]
Type=simple
EnvironmentFile=%h/.config/hermes-eink-dashboard/host.env
Environment=PYTHONPATH=
ExecStart=%h/.local/share/hermes-eink-dashboard/venv/bin/hermes-kindle-dashboard
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now hermes-eink-dashboard.service

# Wait briefly for the health endpoint.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if curl -fsS --max-time 2 "http://$BIND_HOST:$PORT/healthz" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

cat <<EOF
✓ Hermes E-Ink Dashboard installed and running.

  Service:    systemctl --user status hermes-eink-dashboard
  Bind:       http://$BIND_HOST:$PORT
  Token:      $TOKEN_FILE
  Logs:       journalctl --user -u hermes-eink-dashboard -f

Next steps:
  1. Build the Kindle bundle:
       gh repo clone $REPO
       cd ${REPO##*/}
       python3 scripts/build_kual_bundle.py --host $BIND_HOST --port $PORT
  2. Copy dist/hermes-dashboard-kual.zip to your Kindle and install via KUAL.
EOF
